// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC1NQg664yMEGqtjY21rERFH-0Anu7wN8',
    appId: '1:1000546018264:web:c5f5d9a3cc7c78214688ad',
    messagingSenderId: '1000546018264',
    projectId: 'antidoom-on-fire',
    authDomain: 'antidoom-on-fire.firebaseapp.com',
    storageBucket: 'antidoom-on-fire.firebasestorage.app',
    measurementId: 'G-N5GYMNP7T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbrrwkRTvlq_qn__4brwRaCVODYuREqSk',
    appId: '1:1000546018264:android:271270cd52ee8ca34688ad',
    messagingSenderId: '1000546018264',
    projectId: 'antidoom-on-fire',
    storageBucket: 'antidoom-on-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPWk1pp5jj6ZlHz-bbJSCpwkBoubE65s',
    appId: '1:1000546018264:ios:5e9e5e773fb361e04688ad',
    messagingSenderId: '1000546018264',
    projectId: 'antidoom-on-fire',
    storageBucket: 'antidoom-on-fire.firebasestorage.app',
    iosBundleId: 'com.example.antidoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAPWk1pp5jj6ZlHz-bbJSCpwkBoubE65s',
    appId: '1:1000546018264:ios:5e9e5e773fb361e04688ad',
    messagingSenderId: '1000546018264',
    projectId: 'antidoom-on-fire',
    storageBucket: 'antidoom-on-fire.firebasestorage.app',
    iosBundleId: 'com.example.antidoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC1NQg664yMEGqtjY21rERFH-0Anu7wN8',
    appId: '1:1000546018264:web:55d4a22c6c86d8e74688ad',
    messagingSenderId: '1000546018264',
    projectId: 'antidoom-on-fire',
    authDomain: 'antidoom-on-fire.firebaseapp.com',
    storageBucket: 'antidoom-on-fire.firebasestorage.app',
    measurementId: 'G-C82PZ9GFE9',
  );
}
